name: Deploy Laravel to FTP

on:
  push:
    branches: [main]
      - main  # Adjust branch to trigger workflow (if needed)

jobs:
  deploy:
    runs-on: ubuntu-latest  # Replace with desired runner OS

    steps:
      - uses: actions/checkout@v3  # Checks out your code

      - name: Set up PHP (adjust based on your Laravel version)
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.2'
          extensions: mbstring, exif, pcntl  # Adjust extensions based on your Laravel requirements

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader --no-dev

      - name: Generate Laravel Application Key (if needed)
        run: php artisan key:generate  # Uncomment if your application doesn't have a key

      - name: Clear Laravel Cache (optional)
        run: php artisan cache:clear  # Uncomment to clear cache before deployment

      - name: Clear Laravel Config Cache (optional)
        run: php artisan config:cache  # Uncomment to clear config cache before deployment

      - name: Deploy to FTP (securely using GitHub Secrets)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          host: ${{ secrets.SFTP_HOST }}  # Use hostname for SFTP (might be same as FTP)
          username: ${{ secrets.FTP_USERNAME }}  # Reference username from GitHub Secrets
          password: ${{ secrets.FTP_PASSWORD }}  # Reference password from GitHub Secrets
          local-dir: public  # Assuming your Laravel public directory contains deployable files
          remote-dir: /public_html  # Replace with desired directory on the server (adjust for SFTP)
          log-level: verbose  # Adjust logging level as needed
