name: Deploy Laravel to FTP

on:
  push:
    branches:
      - main  # Only trigger on pushes to the main branch

jobs:
  web-deploy:  # Name of the job
    name: deploy  # Descriptive name for the job
    runs-on: ubuntu-latest  # Run the job on Ubuntu machines

    steps:
      - name: Get the latest code  # Clear step description
        uses: actions/checkout@v2.3.2  # Use the checkout action

      - name: Setup Node.js  # Descriptive step description
        uses: actions/setup-node@v3  # Use the setup-node action with a specific version
        with:
          node-version: '18'  # Specify the Node.js version

      - name: Install npm dependencies
        run: npm install  # Install npm dependencies

      - name: Build assets with Vite
        run: npm run build  # Build the assets for production using Vite

      - name: Copy .env file (adjust path if necessary)
        run: php -r "file_exists('.env') || copy('.env.example','.env');"  # Copy .env if not present

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader  # Install composer dependencies

      - name: Generate key
        run: php artisan key:generate  # Generate application key

      - name: Set directory permissions (caution, adjust if needed)
        run: chmod -R 755 storage bootstrap/cache  # Set permissions (consider 755 for security)

      - name: Deploy to cPanel with FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.0.0  # Use the FTP deploy action
        with:
          server: ${{ secrets.FTP_SERVER }}  # Use secrets for server address
          username: ${{ secrets.FTP_USERNAME }}  # Use secrets for username
          password: ${{ secrets.FTP_PASSWORD }}  # Use secrets for password
          server-dir: /public_html/bons/  # Deploy to root directory on the server

      - name: Print npm debug log if npm install or build fails
        if: failure()
        run: cat /home/runner/.npm/_logs/*-debug-*.log
